events {}

http {

    upstream backend_servers {
        server website1:80;
        server website2:80;
    }

    server {
        listen 80;

        server_name www.amanpractice.work.gd;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {

        listen 443 ssl;

        server_name www.amanpractice.work.gd;

        ssl_certificate /etc/letsencrypt/live/www.amanpractice.work.gd/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/www.amanpractice.work.gd/privkey.pem;

        location / {
            proxy_pass http://backend_servers;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
