version = 5.6.0
archive_dir = /etc/letsencrypt/archive/www.amanpractice.work.gd
cert = /etc/letsencrypt/live/www.amanpractice.work.gd/cert.pem
privkey = /etc/letsencrypt/live/www.amanpractice.work.gd/privkey.pem
chain = /etc/letsencrypt/live/www.amanpractice.work.gd/chain.pem
fullchain = /etc/letsencrypt/live/www.amanpractice.work.gd/fullchain.pem
[renewalparams]
account = 35f1137ad254b26311e8c109a2662e05
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
www.amanpractice.work.gd = /var/www/certbot
